const taskData = [
  {
    id: 1,
    title: "Site Preparation",
    description:
      "Clear and prepare the site for construction, including demolition of existing structures.",
    task_type: "Milestone",
    priority: "LVL1",
    employees: [
      { id: 1, name: "John Doe" },
      { id: 2, name: "Jane Smith" },
    ],
    start_date: "Sunday, Sep 1 2024",
    end_date: "Sunday, Sep 13 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#FF0000",
  },
  {
    id: 11,
    title: "Foundation Laying",
    description: "Excavate and lay the foundation for the building structure.",
    task_type: "Milestone",
    priority: "LVL1",
    employees: [
      { id: 1, name: "John Doe" },
      { id: 2, name: "Jane Smith" },
    ],
    start_date: "Sunday, Sep 03 2024",
    end_date: "Sunday, Sep 15 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#FF0000",
  },
  {
    id: 2,
    title: "Concrete Pouring",
    description:
      "Pour concrete for the foundation and ensure it sets properly.",
    priority: "LVL1",
    milestone_parent: 1,
    employees: [
      { id: 3, name: "Tom Brown" },
      { id: 4, name: "Sara White" },
    ],
    start_date: "Sunday, Sep 01 2024",
    end_date: "Sunday, Sep 10 2024",
    predecessor: undefined,
    successor: 3,
    color: "#00FF00",
  },
  {
    id: 3,
    title: "Framing",
    description:
      "Construct the framework for the building including walls and roof.",
    priority: "LVL1",
    milestone_parent: 1,
    employees: [
      { id: 5, name: "Alice Green" },
      { id: 6, name: "Bob Blue" },
    ],
    start_date: "Sunday, Sep 12 2024",
    end_date: "Sunday, Sep 13 2024",
    predecessor: 2,
    successor: 4,
    color: "#8500ff",
  },
  {
    id: 4,
    title: "Roof Installation",
    description: "Install roofing materials and ensure proper waterproofing.",
    priority: "LVL1",
    milestone_parent: 11,
    employees: [
      { id: 7, name: "Charlie Yellow" },
      { id: 8, name: "Diana Red" },
    ],
    start_date: "Sunday, Sep 3 2024",
    end_date: "Sunday, Sep 15 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#008000",
  },
  {
    id: 5,
    title: "Electrical Rough-In",
    description: "Install electrical wiring and fixtures before closing walls.",
    task_type: "Milestone",
    priority: "LVL3",
    employees: [
      { id: 9, name: "Emily Purple" },
      { id: 10, name: "Frank Orange" },
    ],
    start_date: "Sunday, Sep 09 2024",
    end_date: "Sunday, Sep 30 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#FFFF00",
  },
  {
    id: 6,
    title: "Plumbing Installation",
    description:
      "Install plumbing systems and fixtures throughout the building.",
    priority: "LVL3",
    milestone_parent: 5,
    employees: [
      { id: 9, name: "Emily Purple" },
      { id: 10, name: "Frank Orange" },
    ],
    start_date: "Sunday, Sep 09 2024",
    end_date: "Sunday, Sep 11 2024",
    predecessor: undefined,
    successor: 7,
    color: "#FFFF00",
  },
  {
    id: 7,
    title: "Interior Drywall",
    description: "Install drywall and prepare for painting and finishing.",
    priority: "LVL3",
    milestone_parent: 5,
    employees: [
      { id: 3, name: "Tom Brown" },
      { id: 4, name: "Sara White" },
    ],
    start_date: "Sunday, Sep 12 2024",
    end_date: "Sunday, Sep 15 2024",
    predecessor: 6,
    successor: 8,
    color: "#00FF00",
  },
  {
    id: 8,
    title: "Final Finishing",
    description:
      "Complete painting, flooring, and final touches to the interior.",
    priority: "LVL3",
    milestone_parent: 5,
    employees: [
      { id: 9, name: "Emily Purple" },
      { id: 10, name: "Frank Orange" },
    ],
    start_date: "Sunday, Sep 16 2024",
    end_date: "Sunday, Sep 30 2024",
    predecessor: 7,
    successor: undefined,
    color: "#FFFF00",
  },
  {
    id: 9,
    title: "Final Inspection",
    description: "Conduct a final inspection of the completed building.",
    task_type: "Milestone",
    priority: "LVL5",
    employees: [
      { id: 1, name: "John Doe" },
      { id: 2, name: "Jane Smith" },
    ],
    start_date: "Sunday, Sep 5 2024",
    end_date: "Sunday, Sep 10 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#FF0000",
  },
  {
    id: 10,
    title: "Project Handover",
    description: "Official handover of the project to the client.",
    priority: "LVL5",
    milestone_parent: 9,
    employees: [
      { id: 1, name: "John Doe" },
      { id: 2, name: "Jane Smith" },
    ],
    start_date: "Sunday, Sep 05 2024",
    end_date: "Sunday, Sep 10 2024",
    predecessor: undefined,
    successor: undefined,
    color: "#FF0000",
  },
];

export default taskData;
